INSERT INTO countries VALUES('AD','AND',20,'AN','Andorra','ca');
INSERT INTO countries VALUES('AE','ARE',784,'AE','United Arab Emirates','ar-AE,fa,en,hi,ur');
INSERT INTO countries VALUES('AF','AFG',4,'AF','Afghanistan','fa-AF,ps,uz-AF,tk');
INSERT INTO countries VALUES('AG','ATG',28,'AC','Antigua and Barbuda','en-AG');
INSERT INTO countries VALUES('AI','AIA',660,'AV','Anguilla','en-AI');
INSERT INTO countries VALUES('AL','ALB',8,'AL','Albania','sq,el');
INSERT INTO countries VALUES('AM','ARM',51,'AM','Armenia','hy');
INSERT INTO countries VALUES('AO','AGO',24,'AO','Angola','pt-AO');
INSERT INTO countries VALUES('AQ','ATA',10,'AY','Antarctica','');
INSERT INTO countries VALUES('AR','ARG',32,'AR','Argentina','es-AR,en,it,de,fr,gn');
INSERT INTO countries VALUES('AS','ASM',16,'AQ','American Samoa','en-AS,sm,to');
INSERT INTO countries VALUES('AT','AUT',40,'AU','Austria','de-AT,hr,hu,sl');
INSERT INTO countries VALUES('AU','AUS',36,'AS','Australia','en-AU');
INSERT INTO countries VALUES('AW','ABW',533,'AA','Aruba','nl-AW,es,en');
INSERT INTO countries VALUES('AX','ALA',248,'','Aland Islands','sv-AX');
INSERT INTO countries VALUES('AZ','AZE',31,'AJ','Azerbaijan','az,ru,hy');
INSERT INTO countries VALUES('BA','BIH',70,'BK','Bosnia and Herzegovina','bs,hr-BA,sr-BA');
INSERT INTO countries VALUES('BB','BRB',52,'BB','Barbados','en-BB');
INSERT INTO countries VALUES('BD','BGD',50,'BG','Bangladesh','bn-BD,en');
INSERT INTO countries VALUES('BE','BEL',56,'BE','Belgium','nl-BE,fr-BE,de-BE');
INSERT INTO countries VALUES('BF','BFA',854,'UV','Burkina Faso','fr-BF');
INSERT INTO countries VALUES('BG','BGR',100,'BU','Bulgaria','bg,tr-BG,rom');
INSERT INTO countries VALUES('BH','BHR',48,'BA','Bahrain','ar-BH,en,fa,ur');
INSERT INTO countries VALUES('BI','BDI',108,'BY','Burundi','fr-BI,rn');
INSERT INTO countries VALUES('BJ','BEN',204,'BN','Benin','fr-BJ');
INSERT INTO countries VALUES('BL','BLM',652,'TB','Saint Barthelemy','fr');
INSERT INTO countries VALUES('BM','BMU',60,'BD','Bermuda','en-BM,pt');
INSERT INTO countries VALUES('BN','BRN',96,'BX','Brunei','ms-BN,en-BN');
INSERT INTO countries VALUES('BO','BOL',68,'BL','Bolivia','es-BO,qu,ay');
INSERT INTO countries VALUES('BQ','BES',535,'','Bonaire',' Saint Eustatius and Saba ');
INSERT INTO countries VALUES('BR','BRA',76,'BR','Brazil','pt-BR,es,en,fr');
INSERT INTO countries VALUES('BS','BHS',44,'BF','Bahamas','en-BS');
INSERT INTO countries VALUES('BT','BTN',64,'BT','Bhutan','dz');
INSERT INTO countries VALUES('BV','BVT',74,'BV','Bouvet Island','');
INSERT INTO countries VALUES('BW','BWA',72,'BC','Botswana','en-BW,tn-BW');
INSERT INTO countries VALUES('BY','BLR',112,'BO','Belarus','be,ru');
INSERT INTO countries VALUES('BZ','BLZ',84,'BH','Belize','en-BZ,es');
INSERT INTO countries VALUES('CA','CAN',124,'CA','Canada','en-CA,fr-CA,iu');
INSERT INTO countries VALUES('CC','CCK',166,'CK','Cocos Islands','ms-CC,en');
INSERT INTO countries VALUES('CD','COD',180,'CG','Democratic Republic of the Congo','fr-CD,ln,kg');
INSERT INTO countries VALUES('CF','CAF',140,'CT','Central African Republic','fr-CF,sg,ln,kg');
INSERT INTO countries VALUES('CG','COG',178,'CF','Republic of the Congo','fr-CG,kg,ln-CG');
INSERT INTO countries VALUES('CH','CHE',756,'SZ','Switzerland','de-CH,fr-CH,it-CH,rm');
INSERT INTO countries VALUES('CI','CIV',384,'IV','Ivory Coast','fr-CI');
INSERT INTO countries VALUES('CK','COK',184,'CW','Cook Islands','en-CK,mi');
INSERT INTO countries VALUES('CL','CHL',152,'CI','Chile','es-CL');
INSERT INTO countries VALUES('CM','CMR',120,'CM','Cameroon','en-CM,fr-CM');
INSERT INTO countries VALUES('CN','CHN',156,'CH','China','zh-CN,yue,wuu,dta,ug,za');
INSERT INTO countries VALUES('CO','COL',170,'CO','Colombia','es-CO');
INSERT INTO countries VALUES('CR','CRI',188,'CS','Costa Rica','es-CR,en');
INSERT INTO countries VALUES('CU','CUB',192,'CU','Cuba','es-CU');
INSERT INTO countries VALUES('CV','CPV',132,'CV','Cape Verde','pt-CV');
INSERT INTO countries VALUES('CW','CUW',531,'UC','Curacao','nl,pap');
INSERT INTO countries VALUES('CX','CXR',162,'KT','Christmas Island','en,zh,ms-CC');
INSERT INTO countries VALUES('CY','CYP',196,'CY','Cyprus','el-CY,tr-CY,en');
INSERT INTO countries VALUES('CZ','CZE',203,'EZ','Czechia','cs,sk');
INSERT INTO countries VALUES('DE','DEU',276,'GM','Germany','de');
INSERT INTO countries VALUES('DJ','DJI',262,'DJ','Djibouti','fr-DJ,ar,so-DJ,aa');
INSERT INTO countries VALUES('DK','DNK',208,'DA','Denmark','da-DK,en,fo,de-DK');
INSERT INTO countries VALUES('DM','DMA',212,'DO','Dominica','en-DM');
INSERT INTO countries VALUES('DO','DOM',214,'DR','Dominican Republic','es-DO');
INSERT INTO countries VALUES('DZ','DZA',12,'AG','Algeria','ar-DZ');
INSERT INTO countries VALUES('EC','ECU',218,'EC','Ecuador','es-EC');
INSERT INTO countries VALUES('EE','EST',233,'EN','Estonia','et,ru');
INSERT INTO countries VALUES('EG','EGY',818,'EG','Egypt','ar-EG,en,fr');
INSERT INTO countries VALUES('EH','ESH',732,'WI','Western Sahara','ar,mey');
INSERT INTO countries VALUES('ER','ERI',232,'ER','Eritrea','aa-ER,ar,tig,kun,ti-ER');
INSERT INTO countries VALUES('ES','ESP',724,'SP','Spain','es-ES,ca,gl,eu,oc');
INSERT INTO countries VALUES('ET','ETH',231,'ET','Ethiopia','am,en-ET,om-ET,ti-ET,so-ET,sid');
INSERT INTO countries VALUES('FI','FIN',246,'FI','Finland','fi-FI,sv-FI,smn');
INSERT INTO countries VALUES('FJ','FJI',242,'FJ','Fiji','en-FJ,fj');
INSERT INTO countries VALUES('FK','FLK',238,'FK','Falkland Islands','en-FK');
INSERT INTO countries VALUES('FM','FSM',583,'FM','Micronesia','en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg');
INSERT INTO countries VALUES('FO','FRO',234,'FO','Faroe Islands','fo,da-FO');
INSERT INTO countries VALUES('FR','FRA',250,'FR','France','fr-FR,frp,br,co,ca,eu,oc');
INSERT INTO countries VALUES('GA','GAB',266,'GB','Gabon','fr-GA');
INSERT INTO countries VALUES('GB','GBR',826,'UK','United Kingdom','en-GB,cy-GB,gd');
INSERT INTO countries VALUES('GD','GRD',308,'GJ','Grenada','en-GD');
INSERT INTO countries VALUES('GE','GEO',268,'GG','Georgia','ka,ru,hy,az');
INSERT INTO countries VALUES('GF','GUF',254,'FG','French Guiana','fr-GF');
INSERT INTO countries VALUES('GG','GGY',831,'GK','Guernsey','en,fr');
INSERT INTO countries VALUES('GH','GHA',288,'GH','Ghana','en-GH,ak,ee,tw');
INSERT INTO countries VALUES('GI','GIB',292,'GI','Gibraltar','en-GI,es,it,pt');
INSERT INTO countries VALUES('GL','GRL',304,'GL','Greenland','kl,da-GL,en');
INSERT INTO countries VALUES('GM','GMB',270,'GA','Gambia','en-GM,mnk,wof,wo,ff');
INSERT INTO countries VALUES('GN','GIN',324,'GV','Guinea','fr-GN');
INSERT INTO countries VALUES('GP','GLP',312,'GP','Guadeloupe','fr-GP');
INSERT INTO countries VALUES('GQ','GNQ',226,'EK','Equatorial Guinea','es-GQ,fr');
INSERT INTO countries VALUES('GR','GRC',300,'GR','Greece','el-GR,en,fr');
INSERT INTO countries VALUES('GS','SGS',239,'SX','South Georgia and the South Sandwich Islands','en');
INSERT INTO countries VALUES('GT','GTM',320,'GT','Guatemala','es-GT');
INSERT INTO countries VALUES('GU','GUM',316,'GQ','Guam','en-GU,ch-GU');
INSERT INTO countries VALUES('GW','GNB',624,'PU','Guinea-Bissau','pt-GW,pov');
INSERT INTO countries VALUES('GY','GUY',328,'GY','Guyana','en-GY');
INSERT INTO countries VALUES('HK','HKG',344,'HK','Hong Kong','zh-HK,yue,zh,en');
INSERT INTO countries VALUES('HM','HMD',334,'HM','Heard Island and McDonald Islands','');
INSERT INTO countries VALUES('HN','HND',340,'HO','Honduras','es-HN');
INSERT INTO countries VALUES('HR','HRV',191,'HR','Croatia','hr-HR,sr');
INSERT INTO countries VALUES('HT','HTI',332,'HA','Haiti','ht,fr-HT');
INSERT INTO countries VALUES('HU','HUN',348,'HU','Hungary','hu-HU');
INSERT INTO countries VALUES('ID','IDN',360,'ID','Indonesia','id,en,nl,jv');
INSERT INTO countries VALUES('IE','IRL',372,'EI','Ireland','en-IE,ga-IE');
INSERT INTO countries VALUES('IL','ISR',376,'IS','Israel','he,ar-IL,en-IL,');
INSERT INTO countries VALUES('IM','IMN',833,'IM','Isle of Man','en,gv');
INSERT INTO countries VALUES('IN','IND',356,'IN','India','en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc');
INSERT INTO countries VALUES('IO','IOT',86,'IO','British Indian Ocean Territory','en-IO');
INSERT INTO countries VALUES('IQ','IRQ',368,'IZ','Iraq','ar-IQ,ku,hy');
INSERT INTO countries VALUES('IR','IRN',364,'IR','Iran','fa-IR,ku');
INSERT INTO countries VALUES('IS','ISL',352,'IC','Iceland','is,en,de,da,sv,no');
INSERT INTO countries VALUES('IT','ITA',380,'IT','Italy','it-IT,de-IT,fr-IT,sc,ca,co,sl');
INSERT INTO countries VALUES('JE','JEY',832,'JE','Jersey','en,pt');
INSERT INTO countries VALUES('JM','JAM',388,'JM','Jamaica','en-JM');
INSERT INTO countries VALUES('JO','JOR',400,'JO','Jordan','ar-JO,en');
INSERT INTO countries VALUES('JP','JPN',392,'JA','Japan','ja');
INSERT INTO countries VALUES('KE','KEN',404,'KE','Kenya','en-KE,sw-KE');
INSERT INTO countries VALUES('KG','KGZ',417,'KG','Kyrgyzstan','ky,uz,ru');
INSERT INTO countries VALUES('KH','KHM',116,'CB','Cambodia','km,fr,en');
INSERT INTO countries VALUES('KI','KIR',296,'KR','Kiribati','en-KI,gil');
INSERT INTO countries VALUES('KM','COM',174,'CN','Comoros','ar,fr-KM');
INSERT INTO countries VALUES('KN','KNA',659,'SC','Saint Kitts and Nevis','en-KN');
INSERT INTO countries VALUES('KP','PRK',408,'KN','North Korea','ko-KP');
INSERT INTO countries VALUES('KR','KOR',410,'KS','South Korea','ko-KR,en');
INSERT INTO countries VALUES('XK','XKX',0,'KV','Kosovo','sq,sr');
INSERT INTO countries VALUES('KW','KWT',414,'KU','Kuwait','ar-KW,en');
INSERT INTO countries VALUES('KY','CYM',136,'CJ','Cayman Islands','en-KY');
INSERT INTO countries VALUES('KZ','KAZ',398,'KZ','Kazakhstan','kk,ru');
INSERT INTO countries VALUES('LA','LAO',418,'LA','Laos','lo,fr,en');
INSERT INTO countries VALUES('LB','LBN',422,'LE','Lebanon','ar-LB,fr-LB,en,hy');
INSERT INTO countries VALUES('LC','LCA',662,'ST','Saint Lucia','en-LC');
INSERT INTO countries VALUES('LI','LIE',438,'LS','Liechtenstein','de-LI');
INSERT INTO countries VALUES('LK','LKA',144,'CE','Sri Lanka','si,ta,en');
INSERT INTO countries VALUES('LR','LBR',430,'LI','Liberia','en-LR');
INSERT INTO countries VALUES('LS','LSO',426,'LT','Lesotho','en-LS,st,zu,xh');
INSERT INTO countries VALUES('LT','LTU',440,'LH','Lithuania','lt,ru,pl');
INSERT INTO countries VALUES('LU','LUX',442,'LU','Luxembourg','lb,de-LU,fr-LU');
INSERT INTO countries VALUES('LV','LVA',428,'LG','Latvia','lv,ru,lt');
INSERT INTO countries VALUES('LY','LBY',434,'LY','Libya','ar-LY,it,en');
INSERT INTO countries VALUES('MA','MAR',504,'MO','Morocco','ar-MA,fr');
INSERT INTO countries VALUES('MC','MCO',492,'MN','Monaco','fr-MC,en,it');
INSERT INTO countries VALUES('MD','MDA',498,'MD','Moldova','ro,ru,gag,tr');
INSERT INTO countries VALUES('ME','MNE',499,'MJ','Montenegro','sr,hu,bs,sq,hr,rom');
INSERT INTO countries VALUES('MF','MAF',663,'RN','Saint Martin','fr');
INSERT INTO countries VALUES('MG','MDG',450,'MA','Madagascar','fr-MG,mg');
INSERT INTO countries VALUES('MH','MHL',584,'RM','Marshall Islands','mh,en-MH');
INSERT INTO countries VALUES('MK','MKD',807,'MK','Macedonia','mk,sq,tr,rmm,sr');
INSERT INTO countries VALUES('ML','MLI',466,'ML','Mali','fr-ML,bm');
INSERT INTO countries VALUES('MM','MMR',104,'BM','Myanmar','my');
INSERT INTO countries VALUES('MN','MNG',496,'MG','Mongolia','mn,ru');
INSERT INTO countries VALUES('MO','MAC',446,'MC','Macao','zh,zh-MO,pt');
INSERT INTO countries VALUES('MP','MNP',580,'CQ','Northern Mariana Islands','fil,tl,zh,ch-MP,en-MP');
INSERT INTO countries VALUES('MQ','MTQ',474,'MB','Martinique','fr-MQ');
INSERT INTO countries VALUES('MR','MRT',478,'MR','Mauritania','ar-MR,fuc,snk,fr,mey,wo');
INSERT INTO countries VALUES('MS','MSR',500,'MH','Montserrat','en-MS');
INSERT INTO countries VALUES('MT','MLT',470,'MT','Malta','mt,en-MT');
INSERT INTO countries VALUES('MU','MUS',480,'MP','Mauritius','en-MU,bho,fr');
INSERT INTO countries VALUES('MV','MDV',462,'MV','Maldives','dv,en');
INSERT INTO countries VALUES('MW','MWI',454,'MI','Malawi','ny,yao,tum,swk');
INSERT INTO countries VALUES('MX','MEX',484,'MX','Mexico','es-MX');
INSERT INTO countries VALUES('MY','MYS',458,'MY','Malaysia','ms-MY,en,zh,ta,te,ml,pa,th');
INSERT INTO countries VALUES('MZ','MOZ',508,'MZ','Mozambique','pt-MZ,vmw');
INSERT INTO countries VALUES('NA','NAM',516,'WA','Namibia','en-NA,af,de,hz,naq');
INSERT INTO countries VALUES('NC','NCL',540,'NC','New Caledonia','fr-NC');
INSERT INTO countries VALUES('NE','NER',562,'NG','Niger','fr-NE,ha,kr,dje');
INSERT INTO countries VALUES('NF','NFK',574,'NF','Norfolk Island','en-NF');
INSERT INTO countries VALUES('NG','NGA',566,'NI','Nigeria','en-NG,ha,yo,ig,ff');
INSERT INTO countries VALUES('NI','NIC',558,'NU','Nicaragua','es-NI,en');
INSERT INTO countries VALUES('NL','NLD',528,'NL','Netherlands','nl-NL,fy-NL');
INSERT INTO countries VALUES('NO','NOR',578,'NO','Norway','no,nb,nn,se,fi');
INSERT INTO countries VALUES('NP','NPL',524,'NP','Nepal','ne,en');
INSERT INTO countries VALUES('NR','NRU',520,'NR','Nauru','na,en-NR');
INSERT INTO countries VALUES('NU','NIU',570,'NE','Niue','niu,en-NU');
INSERT INTO countries VALUES('NZ','NZL',554,'NZ','New Zealand','en-NZ,mi');
INSERT INTO countries VALUES('OM','OMN',512,'MU','Oman','ar-OM,en,bal,ur');
INSERT INTO countries VALUES('PA','PAN',591,'PM','Panama','es-PA,en');
INSERT INTO countries VALUES('PE','PER',604,'PE','Peru','es-PE,qu,ay');
INSERT INTO countries VALUES('PF','PYF',258,'FP','French Polynesia','fr-PF,ty');
INSERT INTO countries VALUES('PG','PNG',598,'PP','Papua New Guinea','en-PG,ho,meu,tpi');
INSERT INTO countries VALUES('PH','PHL',608,'RP','Philippines','tl,en-PH,fil');
INSERT INTO countries VALUES('PK','PAK',586,'PK','Pakistan','ur-PK,en-PK,pa,sd,ps,brh');
INSERT INTO countries VALUES('PL','POL',616,'PL','Poland','pl');
INSERT INTO countries VALUES('PM','SPM',666,'SB','Saint Pierre and Miquelon','fr-PM');
INSERT INTO countries VALUES('PN','PCN',612,'PC','Pitcairn','en-PN');
INSERT INTO countries VALUES('PR','PRI',630,'RQ','Puerto Rico','en-PR,es-PR');
INSERT INTO countries VALUES('PS','PSE',275,'WE','Palestinian Territory','ar-PS');
INSERT INTO countries VALUES('PT','PRT',620,'PO','Portugal','pt-PT,mwl');
INSERT INTO countries VALUES('PW','PLW',585,'PS','Palau','pau,sov,en-PW,tox,ja,fil,zh');
INSERT INTO countries VALUES('PY','PRY',600,'PA','Paraguay','es-PY,gn');
INSERT INTO countries VALUES('QA','QAT',634,'QA','Qatar','ar-QA,es');
INSERT INTO countries VALUES('RE','REU',638,'RE','Reunion','fr-RE');
INSERT INTO countries VALUES('RO','ROU',642,'RO','Romania','ro,hu,rom');
INSERT INTO countries VALUES('RS','SRB',688,'RI','Serbia','sr,hu,bs,rom');
INSERT INTO countries VALUES('RU','RUS',643,'RS','Russia','ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog');
INSERT INTO countries VALUES('RW','RWA',646,'RW','Rwanda','rw,en-RW,fr-RW,sw');
INSERT INTO countries VALUES('SA','SAU',682,'SA','Saudi Arabia','ar-SA');
INSERT INTO countries VALUES('SB','SLB',90,'BP','Solomon Islands','en-SB,tpi');
INSERT INTO countries VALUES('SC','SYC',690,'SE','Seychelles','en-SC,fr-SC');
INSERT INTO countries VALUES('SD','SDN',729,'SU','Sudan','ar-SD,en,fia');
INSERT INTO countries VALUES('SS','SSD',728,'OD','South Sudan','en');
INSERT INTO countries VALUES('SE','SWE',752,'SW','Sweden','sv-SE,se,sma,fi-SE');
INSERT INTO countries VALUES('SG','SGP',702,'SN','Singapore','cmn,en-SG,ms-SG,ta-SG,zh-SG');
INSERT INTO countries VALUES('SH','SHN',654,'SH','Saint Helena','en-SH');
INSERT INTO countries VALUES('SI','SVN',705,'SI','Slovenia','sl,sh');
INSERT INTO countries VALUES('SJ','SJM',744,'SV','Svalbard and Jan Mayen','no,ru');
INSERT INTO countries VALUES('SK','SVK',703,'LO','Slovakia','sk,hu');
INSERT INTO countries VALUES('SL','SLE',694,'SL','Sierra Leone','en-SL,men,tem');
INSERT INTO countries VALUES('SM','SMR',674,'SM','San Marino','it-SM');
INSERT INTO countries VALUES('SN','SEN',686,'SG','Senegal','fr-SN,wo,fuc,mnk');
INSERT INTO countries VALUES('SO','SOM',706,'SO','Somalia','so-SO,ar-SO,it,en-SO');
INSERT INTO countries VALUES('SR','SUR',740,'NS','Suriname','nl-SR,en,srn,hns,jv');
INSERT INTO countries VALUES('ST','STP',678,'TP','Sao Tome and Principe','pt-ST');
INSERT INTO countries VALUES('SV','SLV',222,'ES','El Salvador','es-SV');
INSERT INTO countries VALUES('SX','SXM',534,'NN','Sint Maarten','nl,en');
INSERT INTO countries VALUES('SY','SYR',760,'SY','Syria','ar-SY,ku,hy,arc,fr,en');
INSERT INTO countries VALUES('SZ','SWZ',748,'WZ','Swaziland','en-SZ,ss-SZ');
INSERT INTO countries VALUES('TC','TCA',796,'TK','Turks and Caicos Islands','en-TC');
INSERT INTO countries VALUES('TD','TCD',148,'CD','Chad','fr-TD,ar-TD,sre');
INSERT INTO countries VALUES('TF','ATF',260,'FS','French Southern Territories','fr');
INSERT INTO countries VALUES('TG','TGO',768,'TO','Togo','fr-TG,ee,hna,kbp,dag,ha');
INSERT INTO countries VALUES('TH','THA',764,'TH','Thailand','th,en');
INSERT INTO countries VALUES('TJ','TJK',762,'TI','Tajikistan','tg,ru');
INSERT INTO countries VALUES('TK','TKL',772,'TL','Tokelau','tkl,en-TK');
INSERT INTO countries VALUES('TL','TLS',626,'TT','East Timor','tet,pt-TL,id,en');
INSERT INTO countries VALUES('TM','TKM',795,'TX','Turkmenistan','tk,ru,uz');
INSERT INTO countries VALUES('TN','TUN',788,'TS','Tunisia','ar-TN,fr');
INSERT INTO countries VALUES('TO','TON',776,'TN','Tonga','to,en-TO');
INSERT INTO countries VALUES('TR','TUR',792,'TU','Turkey','tr-TR,ku,diq,az,av');
INSERT INTO countries VALUES('TT','TTO',780,'TD','Trinidad and Tobago','en-TT,hns,fr,es,zh');
INSERT INTO countries VALUES('TV','TUV',798,'TV','Tuvalu','tvl,en,sm,gil');
INSERT INTO countries VALUES('TW','TWN',158,'TW','Taiwan','zh-TW,zh,nan,hak');
INSERT INTO countries VALUES('TZ','TZA',834,'TZ','Tanzania','sw-TZ,en,ar');
INSERT INTO countries VALUES('UA','UKR',804,'UP','Ukraine','uk,ru-UA,rom,pl,hu');
INSERT INTO countries VALUES('UG','UGA',800,'UG','Uganda','en-UG,lg,sw,ar');
INSERT INTO countries VALUES('UM','UMI',581,'','United States Minor Outlying Islands','en-UM');
INSERT INTO countries VALUES('US','USA',840,'US','United States','en-US,es-US,haw,fr');
INSERT INTO countries VALUES('UY','URY',858,'UY','Uruguay','es-UY');
INSERT INTO countries VALUES('UZ','UZB',860,'UZ','Uzbekistan','uz,ru,tg');
INSERT INTO countries VALUES('VA','VAT',336,'VT','Vatican','la,it,fr');
INSERT INTO countries VALUES('VC','VCT',670,'VC','Saint Vincent and the Grenadines','en-VC,fr');
INSERT INTO countries VALUES('VE','VEN',862,'VE','Venezuela','es-VE');
INSERT INTO countries VALUES('VG','VGB',92,'VI','British Virgin Islands','en-VG');
INSERT INTO countries VALUES('VI','VIR',850,'VQ','U.S. Virgin Islands','en-VI');
INSERT INTO countries VALUES('VN','VNM',704,'VM','Vietnam','vi,en,fr,zh,km');
INSERT INTO countries VALUES('VU','VUT',548,'NH','Vanuatu','bi,en-VU,fr-VU');
INSERT INTO countries VALUES('WF','WLF',876,'WF','Wallis and Futuna','wls,fud,fr-WF');
INSERT INTO countries VALUES('WS','WSM',882,'WS','Samoa','sm,en-WS');
INSERT INTO countries VALUES('YE','YEM',887,'YM','Yemen','ar-YE');
INSERT INTO countries VALUES('YT','MYT',175,'MF','Mayotte','fr-YT');
INSERT INTO countries VALUES('ZA','ZAF',710,'SF','South Africa','zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr');
INSERT INTO countries VALUES('ZM','ZMB',894,'ZA','Zambia','en-ZM,bem,loz,lun,lue,ny,toi');
INSERT INTO countries VALUES('ZW','ZWE',716,'ZI','Zimbabwe','en-ZW,sn,nr,nd');
INSERT INTO countries VALUES('CS','SCG',891,'YI','Serbia and Montenegro','cu,hu,sq,sr');
INSERT INTO countries VALUES('AN','ANT',530,'NT','Netherlands Antilles','nl-AN,en,es');
